=== fkujikis/common-jbossxb/jbossxb/branches/1.0.0.GA_CP/src/test/resources/xml/sandbox.xsd
<?xml version="1.0" encoding="utf-8"?>

<xsd:schema
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:sb="http://www.jboss.org/test/xml/sandbox"
   targetNamespace="http://www.jboss.org/test/xml/sandbox"
   elementFormDefault="qualified">

  <xsd:element name="root">
    <xsd:complexType>
      <xsd:sequence>

        <xsd:element name="choiceCollection1" type="sb:choice1" maxOccurs="3"/>

        <xsd:element name="choice2" maxOccurs="2">
          <xsd:complexType>
            <xsd:choice>
              <xsd:sequence>
                <xsd:element name="c" type="xsd:string"/>
                <xsd:element name="d" type="xsd:string"/>
              </xsd:sequence>
              <xsd:sequence>
                <xsd:element name="e" type="xsd:string"/>
                <xsd:element name="d" type="xsd:string"/>
              </xsd:sequence>
            </xsd:choice>
          </xsd:complexType>
        </xsd:element>

        <xsd:element name="choice3" maxOccurs="2">
          <xsd:complexType>
            <xsd:choice>
              <xsd:element name="listOfIntegers" type="xsd:int" maxOccurs="unbounded"/>
              <xsd:element name="listOfStrings" type="xsd:string" maxOccurs="unbounded"/>
            </xsd:choice>
          </xsd:complexType>
        </xsd:element>

      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="choice1">
     <xsd:choice>
        <xsd:element name="a" type="xsd:string"/>
        <xsd:element name="b" type="xsd:string"/>
     </xsd:choice>
  </xsd:complexType>

</xsd:schema>

=== fkujikis/common-jbossxb/jbossxb/branches/1_0/src/test/resources/xml/sandbox.xml
<sb:root
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.jboss.org/test/xml/sandbox sandbox.xsd"
   xmlns:sb="http://www.jboss.org/test/xml/sandbox">

   <sb:choiceCollection1>
      <sb:a>choice1_a</sb:a>
   </sb:choiceCollection1>
   <sb:choiceCollection1>
      <sb:b>choice1_b</sb:b>
   </sb:choiceCollection1>

   <sb:choice2>
      <sb:c>choice2_c</sb:c>
      <sb:d>choice2_d</sb:d>
   </sb:choice2>
   <sb:choice2>
      <sb:e>choice2_e</sb:e>
      <sb:d>choice2_d</sb:d>
   </sb:choice2>

   <sb:choice3>
      <sb:listOfIntegers>1</sb:listOfIntegers>
      <sb:listOfIntegers>2</sb:listOfIntegers>
      <sb:listOfIntegers>3</sb:listOfIntegers>
   </sb:choice3>
   <sb:choice3>
      <sb:listOfStrings>1</sb:listOfStrings>
      <sb:listOfStrings>2</sb:listOfStrings>
      <sb:listOfStrings>3</sb:listOfStrings>
   </sb:choice3>
</sb:root>
